// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0MUt0z5ifwgbyczkFbjH-n7Bh7dhb5lY',
    appId: '1:865650290885:web:3ce22ba6e8846f67c200ac',
    messagingSenderId: '865650290885',
    projectId: 'clever-abbey-384113',
    authDomain: 'clever-abbey-384113.firebaseapp.com',
    databaseURL: 'https://clever-abbey-384113-default-rtdb.firebaseio.com',
    storageBucket: 'clever-abbey-384113.appspot.com',
    measurementId: 'G-PXVY9GWQHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsdnjN7A8Ez6CwcOsQTsBEB-9uL4hhRE',
    appId: '1:865650290885:android:7d5c3ea2f9c0e56bc200ac',
    messagingSenderId: '865650290885',
    projectId: 'clever-abbey-384113',
    databaseURL: 'https://clever-abbey-384113-default-rtdb.firebaseio.com',
    storageBucket: 'clever-abbey-384113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQnbY5DylrR-YHeE7RSojOAhX6vpgGeU',
    appId: '1:865650290885:ios:d07df24bc673438dc200ac',
    messagingSenderId: '865650290885',
    projectId: 'clever-abbey-384113',
    databaseURL: 'https://clever-abbey-384113-default-rtdb.firebaseio.com',
    storageBucket: 'clever-abbey-384113.appspot.com',
    iosClientId:
        '865650290885-t1bqnjuhh9n1l72tjli28njjltpk5fnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRQnbY5DylrR-YHeE7RSojOAhX6vpgGeU',
    appId: '1:865650290885:ios:d07df24bc673438dc200ac',
    messagingSenderId: '865650290885',
    projectId: 'clever-abbey-384113',
    databaseURL: 'https://clever-abbey-384113-default-rtdb.firebaseio.com',
    storageBucket: 'clever-abbey-384113.appspot.com',
    iosClientId:
        '865650290885-t1bqnjuhh9n1l72tjli28njjltpk5fnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventus',
  );
}
